set(sources ${sources}
	src/AudioHooks.cpp
	src/AutoCloseManager.cpp
	src/ConsoleCommandHooks.cpp
	src/Controls/BSWin32KeyboardDeviceEx.cpp
	src/Controls/CameraMovement.cpp
	src/Controls/MenuControlsEx.cpp
	src/Controls/PlayerControlsEx.cpp
	src/ItemMenuUpdater.cpp
	src/MenuCache.cpp
	src/Menus/BarterMenuEx.cpp
	src/Menus/BookMenuEx.cpp
	src/Menus/CombatAlertOverlayMenu.cpp
	src/Menus/ConsoleEx.cpp
	src/Menus/ContainerMenuEx.cpp
	src/Menus/CustomMenuEx.cpp
	src/Menus/DialogueMenuEx.cpp
	src/Menus/FavoritesMenuEx.cpp
	src/Menus/GiftMenuEx.cpp
	src/Menus/HUDMenuEx.cpp
	src/Menus/InventoryMenuEx.cpp
	src/Menus/JournalMenuEx.cpp
	src/Menus/LevelUpMenuEx.cpp
	src/Menus/LockpickingMenuEx.cpp
	src/Menus/MagicMenuEx.cpp
	src/Menus/MapMenuEx.cpp
	src/Menus/MessageBoxMenuEx.cpp
	src/Menus/ModManagerMenuEx.cpp
	src/Menus/SleepWaitMenuEx.cpp
	src/Menus/StatsMenuEx.cpp
	src/Menus/TrainingMenuEx.cpp
	src/Menus/TutorialMenuEx.cpp
	src/Menus/TweenMenuEx.cpp
	src/PCH.cpp
	src/PapyrusHook.cpp
	src/Settings.cpp
	src/SkyrimSoulsRE.cpp
	src/SlowMotionHandler.cpp
	src/UIBlurManagerEx.cpp
	src/UnpausedTaskQueue.cpp
	src/main.cpp
)
